In [ ]:
mport pandas as pd

data = {
    "Student_ID": [101,102,103,104,105,106,107,108,109,110,
                   111,112,113,114,115,116,117,118,119,120],

    "Name": ["Aman","Neha","Rahul","Priya","Karan",
             "Simran","Mohit","Anjali","Vikas","Pooja",
             "Rohit","Sneha","Arjun","Riya","Deepak",
             "Muskan","Yash","Komal","Abhishek","Nisha"],

    "Gender": ["Male","Female","Male","Female","Male",
               "Female","Male","Female","Male","Female",
               "Male","Female","Male","Female","Male",
               "Female","Male","Female","Male","Female"],

    "Age": [20,21,19,22,20,21,20,19,22,20,
            21,20,23,19,22,20,21,22,20,19],

    "Department": ["CSE","IT","ECE","CSE","IT",
                   "CSE","ECE","IT","CSE","ECE",
                   "IT","CSE","ECE","IT","CSE",
                   "ECE","IT","CSE","ECE","IT"],

    "Semester": [4,4,2,6,4,6,2,4,8,6,
                 2,8,6,4,8,2,6,4,8,2],

    "Marks": [85,92,78,95,67,88,72,91,81,76,
              69,94,73,89,97,66,82,90,79,84],

    "Attendance": [92,95,85,97,78,90,82,98,88,84,
                   80,96,83,91,99,76,89,94,87,92],

    "CGPA": [8.5,9.2,7.8,9.5,6.9,
             8.8,7.2,9.1,8.1,7.6,
             7.0,9.4,7.4,8.9,9.8,
             6.8,8.2,9.0,7.9,8.4],

    "City": ["Delhi","Lucknow","Noida","Jaipur","Delhi",
             "Noida","Lucknow","Delhi","Jaipur","Delhi",
             "Noida","Lucknow","Delhi","Jaipur","Delhi",
             "Noida","Lucknow","Delhi","Jaipur","Delhi"]
}

df = pd.DataFrame(data)

print(df)

In [ ]:
import numpy as np
array = np.array([10,20,30,40,50])
print(array)

[10 20 30 40 50]


In [ ]:
array = np.array([[[10,20],[30,40]],[[50,60],[70,80]]])
print(array)

[[[10 20]
  [30 40]]

 [[50 60]
  [70 80]]]


In [ ]:
print(array.shape)

(2, 2, 2)


In [ ]:
print(array.size)

8


In [ ]:
a = np.array([1,2,3,4,5])
b = np.array([3,4,7,8,9])
print(a+b)
print(a+b)
print(a*b)
print(a/b)
print(a**2)

[ 4  6 10 12 14]
[ 4  6 10 12 14]
[ 3  8 21 32 45]
[0.33333333 0.5        0.42857143 0.5        0.55555556]
[ 1  4  9 16 25]


In [ ]:
print(np.sqrt(a))

[1.         1.41421356 1.73205081 2.         2.23606798]


In [ ]:
print(np.power(a,2))

[ 1  4  9 16 25]


In [ ]:
print(np.max(a))

5


In [ ]:
print(np.sum(a))

15


In [ ]:
print(np.min(a))

1
